version: "3"

services:

  kong:
    image: kong:0.9.9
    networks:
      - backend
    labels:
      pf.gov.tier: "backend"
      pf.gov.kong.role: "gateway"
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: database
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure

  database:
    image: cassandra:2.2
    networks:
      - backend
    labels:
      pf.gov.tier: "backend"
      pf.gov.kong.role: "database"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure

  dashboard:
    image: pgbi/kong-dashboard:v1.3.1
    networks:
      - backend
    labels:
      pf.gov.tier: "backend"
      pf.gov.kong.role: "dashboard"
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend:
